apiVersion: batch/v1
kind: CronJob
metadata:
  name: check-endpoint-cronjob-basic-auth
spec:
  schedule: "*/5 * * * *"  # A cada 5 minutos
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: check-endpoint
            image: <your-docker-image-basic-auth>:latest
            command: ["/bin/sh"]
            args:
              - "-c"
              - "/usr/local/bin/check_endpoint.sh $ENDPOINT_URL $BASIC_AUTH_USERNAME $BASIC_AUTH_PASSWORD"
            env:
            - name: ENDPOINT_URL
              value: "https://example.com"  # Substitua pela sua URL de endpoint
            - name: BASIC_AUTH_USERNAME
              value: "seu-usuario"           # Substitua pelo nome de usuário para autenticação básica
            - name: BASIC_AUTH_PASSWORD
              value: "sua-senha"             # Substitua pela senha para autenticação básica
          restartPolicy: OnFailure