apiVersion: batch/v1
kind: CronJob
metadata:
  name: check-endpoint-cronjob-bearer-auth
spec:
  schedule: "*/5 * * * *"  # A cada 5 minutos
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: check-endpoint
            image: <your-docker-image-bearer-auth>:latest
            command: ["/bin/sh"]
            args:
              - "-c"
              - "/usr/local/bin/check_endpoint.sh $ENDPOINT_URL $BEARER_TOKEN"
            env:
            - name: ENDPOINT_URL
              value: "https://example.com"  # Substitua pela sua URL de endpoint
            - name: BEARER_TOKEN
              value: "seu-token-bearer"     # Substitua pelo seu token de autenticação Bearer
          restartPolicy: OnFailure
